# Generated by Django 5.2.1 on 2025-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('applicant', 'applicant'), ('recruiter', 'recruiter')], max_length=20),
        ),
    ]
