# Generated by Django 5.2.1 on 2025-05-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customusermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('applicant', 'applicant'), ('recruiter', 'recruiter')], default='applicant', max_length=30),
        ),
    ]
