# Generated by Django 5.2.1 on 2025-05-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=50)),
                ('skills_required', models.TextField(blank=True, help_text='skills required', null=True)),
                ('description', models.TextField(blank=True, help_text='describe about job more', null=True)),
                ('experience_required', models.IntegerField()),
                ('job_type', models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time')])),
                ('job_location_type', models.CharField(choices=[('remote', 'Remote'), ('city', 'City'), ('hybrid', 'Hybrid')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
